#!/bin/sh

USERS=""
adduser() {
	INITUSERS="$USERS"

	[ "$INITUSERS" != "" ] && { 
		USERS="$USERS!$1"
	} || {
		USERS="$1"
	}
}

getusers() {
	compgen -u | grep root > /dev/null && adduser root
	echo $USERS | grep $USER || adduser $USER
	# In the future I should make an option to be able to auto detect more accounts

	USERS="$(echo $USERS | sed "s/$USER/^$USER/g")"
}

check() {
	IFS=""
	VALUES="$(echo -e "$(echo "$1" | sed 's/|/\\n/g')")"

	sudo ispass "$(echo $VALUES | sed 1q)" "$(echo $VALUES | sed 1d | sed 1q)" && {
		return 0
	} || {
		return 1
	}
}

init() {
	getusers
	gtkpass \
		--fixed \
		--icons \
		--on-top \
		--center \
		--focus-field="2" \
		--title="GTKPass" \
		--text-align="center" \
		--buttons-layout="spread" \
		--button="Cancel":1 --button="Sign In":0 \
		--form --field=" Username ":CB "$USERS" --field=" Password ":H 
}; init | check "$(cat -)"
